FROM emscripten/emsdk

# setup enviroments
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=America/Los_Angeles
RUN \
    apt update -y && \
    apt install -y tzdata gcc g++ gdb cmake make python3 nano vim less git

# build opencv into wasm
RUN \
    # download opencv source code
    cd /src && wget https://github.com/opencv/opencv/archive/refs/tags/4.8.0.tar.gz && \
    tar -xzvf 4.8.0.tar.gz && \
    export EMSCRIPTEN="/emsdk/upstream/emscripten" && \
    cd opencv-4.8.0 && mkdir build_wasm && \
    python3 ./platforms/js/build_js.py build_wasm --build_wasm

# setup working dir & copy source code
WORKDIR /src/MoonRegistration
COPY . .

# build MoonRegistration lib into wasm
RUN \
    mkdir /src/MoonRegistration/build_wasm && cd /src/MoonRegistration/build_wasm && \
    emcmake cmake -DMR_BUILD_WASM=ON -DOPENCV_DIR="/src/opencv-4.8.0" .. && \
    emmake make

ENTRYPOINT ["/bin/bash"]
