FROM gavin1937/emsdk-cv-wasm:4.8.0

# setup enviroments
RUN \
    apt update -y && \
    apt install -y nano vim less git

# setup working dir & copy source code
WORKDIR /src/MoonRegistration
COPY . .

# build MoonRegistration lib into wasm
RUN \
    mkdir /src/MoonRegistration/build_wasm && cd /src/MoonRegistration/build_wasm && \
    emcmake cmake -DMR_BUILD_WASM=ON -DOPENCV_DIR="$OPENCV_SRC" .. && \
    emmake make

ENTRYPOINT ["/bin/bash"]
