FROM gavin1937/emsdk-cv-wasm:4.9.0

# setup enviroments
RUN \
    apt update -y && \
    apt install -y libopencv-dev nano vim less git

# setup working dir & copy source code
WORKDIR /src/MoonRegistration
COPY . .

# build MoonRegistration lib in Release Mode
RUN \
    # compile linux version
    mkdir /src/MoonRegistration/build_linux && cd /src/MoonRegistration/build_linux && \
    cmake -DCMAKE_BUILD_TYPE=Release -DMR_BUILD_SHARED_LIBS=OFF .. && \
    cmake --build . && \
    cmake -DCMAKE_BUILD_TYPE=Release -DMR_BUILD_SHARED_LIBS=ON .. && \
    cmake --build . && \
    # compile wasm version
    mkdir /src/MoonRegistration/platforms/js/build_wasm && \
    cd /src/MoonRegistration/platforms/js/build_wasm && \
    emcmake cmake -DCMAKE_BUILD_TYPE=Release -DOPENCV_SRC="$OPENCV_SRC" .. && \
    emmake make && \
    # pack release
    cd /src/MoonRegistration && python3 PackReleaseZip.py

ENTRYPOINT ["/bin/bash"]
