FROM gavin1937/emsdk-cv-wasm:4.9.0

# setup enviroments
RUN \
    apt update -y && \
    apt install -y nano vim less git

# setup working dir & copy source code
WORKDIR /src/MoonRegistration
COPY . .

# build MoonRegistration lib into wasm
RUN \
    mkdir /src/MoonRegistration/platforms/js/build_wasm && \
    cd /src/MoonRegistration/platforms/js/build_wasm && \
    emcmake cmake -DOPENCV_SRC="$OPENCV_SRC" .. && \
    emmake make

ENTRYPOINT ["/bin/bash"]
