FROM ubuntu:22.04

# setup enviroments
ENV DEBIAN_FRONTEND=noninteractive \
    TZ=America/Los_Angeles
RUN \
    apt update -y && \
    apt install -y tzdata gcc g++ gdb cmake make libopencv-dev nano vim less git libboost-all-dev python3 python3-pip

# setup working dir & copy source code
WORKDIR /src/MoonRegistration
COPY . .

# build MoonRegistration lib
RUN cd /src/MoonRegistration && \
    mkdir build && \
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug && cmake --build build && \
    cd platforms/python && \
    pip3 install wheel && python3 setup.py install && \
    python3 setup.py bdist_wheel && python3 setup.py bdist_wheel

ENTRYPOINT ["/bin/bash"]
