name: Pack Release Package

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup ENV
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "VERSION_STR=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    
    - name: Build & Package
      run: docker build -t moonregistration -f ./dockerfiles/release_env.dockerfile .
    
    - name: Create Container
      run: docker create --name moonregistration-container moonregistration
    
    - name: Copy Package Out
      run: |
        docker cp moonregistration-container:"/src/MoonRegistration/archives/" .
    
    - name: Release archives
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: './archives/MoonRegistration*.zip'
        file_glob: true
        overwrite: true
        tag: '${{ env.RELEASE_VERSION }}'

