name: Pack Release Package

on:
  push:
    tags:
      - 'v*.*.*'
      - 'test'

jobs:
  release:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest]
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
    - uses: jwlawson/actions-setup-cmake@v2.0.1
    
    - name: Setup ENV
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        echo "VERSION_STR=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV
    
    # Unix Build using Docker
    - name: Docker Build & Package
      if: matrix.os == 'ubuntu-latest'
      run: docker build -t moonregistration -f ./dockerfiles/release_env.dockerfile .
    
    - name: Docker Create Container
      if: matrix.os == 'ubuntu-latest'
      run: docker create --name moonregistration-container moonregistration
    
    - name: Docker Copy Package Out
      if: matrix.os == 'ubuntu-latest'
      run: |
        docker cp moonregistration-container:"/src/MoonRegistration/archives/" .
    
    # Windows Build
    - name: Windows Get OpenCV
      if: matrix.os == 'windows-latest'
      run: |
        Invoke-WebRequest https://github.com/Gavin1937/win-opencv/releases/download/4.9.0/opencv-4.9.0.zip -OutFile opencv-4.9.0.zip
        7z x opencv-4.9.0.zip -o"opencv-4.9.0"
        $env:OPENCV_DIR="$(pwd)\opencv-4.9.0"
    
    - name: Windows Build & Package
      if: matrix.os == 'windows-latest'
      run: |
        python3 Release.py ./release_config.json
        python3 Release.py ./platforms/python/release_config.json
        mkdir archives
        mv MoonRegistration*.zip ./archives
    
    - name: Release archives
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: './archives/MoonRegistration*.zip'
        file_glob: true
        overwrite: true
        tag: '${{ env.RELEASE_VERSION }}'

